version: '3.8'

volumes:
  db_storage:
  n8n_storage:

networks:
  red-principal:
    external: true

services:
  n8n-init:
    image: postgres:latest
    container_name: n8n_init
    entrypoint: >
      bash -c "
        until pg_isready -h ${POSTGRES_HOST} -U ${POSTGRES_USER}; do
          echo 'Esperando a PostgreSQL...';
          sleep 5;
        done;
        echo 'Verificando existencia de base de datos...';
        psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -tc \"SELECT 1 FROM pg_database WHERE datname = '${POSTGRES_DB}'\" | grep -q 1 || \
        psql -h ${POSTGRES_HOST} -U ${POSTGRES_USER} -c \"CREATE DATABASE \\\"${POSTGRES_DB}\\\";\"
        echo 'Finalizado. Apagando contenedor n8n-init.';
      "
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_storage:/var/lib/postgresql/data
    networks:
      - red-principal
    restart: "no"

  n8n-server:
    image: n8nio/n8n:latest
    container_name: n8n-server
    restart: always
    depends_on:
      - n8n-init
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=public
      - N8N_RUNNERS_ENABLED=true
      - GENERIC_TIMEZONE=America/Bogota
      - TZ=America/Bogota
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
    networks:
      - red-principal
